### ISSUE TITLE
Why this error showing on node .

### ISSUE THREAD

**Issue by MRJ-Badshah** [ELITE-SMOKER-69/GtsNuker#2]
![Uploading Screenshot_2021-11-30-11-25-40-527_com.termux.jpg…]()

**Comment by MRJ-Badshah** [comment]
![Screenshot_2021-11-30-11-25-40-527_com termux](https://user-images.githubusercontent.com/69976020/143993662-b024705e-a05a-4ce3-9eeb-442a8534045c.jpg)

**Comment by MRJ-Badshah** [comment]
![Screenshot_2021-11-30-11-45-41-552_com termux](https://user-images.githubusercontent.com/69976020/143995561-78266008-b77a-4d3e-9dfc-1fae41dfbf91.jpg)

**Comment by Zashiraa** [comment]
its a problem with the chalk module not the tool i'll fix it soon
